#!/bin/bash
#SBATCH -J pr-power           # job name
#SBATCH -o ./output/pr%j       # output and error file name (%j expands to jobID)
#SBATCH -N 1              # total number of nodes
#SBATCH -n 1             # total number of cores
#SBATCH -p gtx     # queue (partition) -- normal, development, etc.
#SBATCH -t 00:20:00        # run time (hh:mm:ss) - 20 seconds
#SBATCH -A EE-382C-EE-361C-Mult

./main.o
